import { Title } from "components"
import type { NextPage } from "next"
import Head from "next/head"

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex h-screen w-full items-center justify-center">
        <Title>Contact Page</Title>
      </div>
    </>
  )
}

export default Contact
