import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { api } from "utils/api"

const Snippet: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const snippet = api.snippet.getOne.useQuery({ id: id as string })
  return (
    <>
      <Head>
        <title>All Snippets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex h-screen w-full items-center justify-center">
        <div>
          <h2 className="mb-6 text-7xl font-bold">
            {"I'm "}
            <span className="text-primary">
              Diogo
              <br />
            </span>
            Nogueira,
          </h2>
          <h1 className="text-xl leading-7 text-textdim">
            a <strong className="font-bold text-text">front-end developer</strong> who chose
            <br /> to hard code his life.
          </h1>
        </div>
      </div>
    </>
  )
}

export default Snippet
