import { CodeBlock, Title } from "components"
import type { NextPage } from "next"
/* import dynamic from "next/dynamic" */
import Head from "next/head"
import { useRouter } from "next/router"
import { api } from "utils/api"

/* const CodeBlock = dynamic(() => import("components").then(module => module.CodeBlock), {
  ssr: false
})
 */
const Snippet: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const { data: snippet } = api.snippet.getOne.useQuery({ id: id as string })

  return (
    <>
      <Head>
        <title>Snippet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex flex-col items-center py-20">
        <Title>
          Viewing a <span className="text-primary">Snippet</span>
        </Title>
        <CodeBlock snippet={snippet} />
      </div>
    </>
  )
}

export default Snippet
