import { CodeBlock } from "components"
import type { NextPage } from "next"
import Head from "next/head"
import { api } from "utils/api"

const Snippets: NextPage = () => {
  const snippets = api.snippet.getAll.useQuery()
  return (
    <>
      <Head>
        <title>All Snippets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex flex-col items-center justify-center py-20">
        <h1 className="mb-8 text-center text-7xl font-bold">
          {"All "}
          <span className="text-primary">Snippets</span>
        </h1>
        <div className="flex flex-col gap-2">
          {snippets?.data?.map((snippet, idx) => (
            <CodeBlock snippet={snippet} />
          ))}
        </div>
      </div>
    </>
  )
}

export default Snippets
