import type { NextPage } from "next"
import Head from "next/head"
import { api } from "utils/api"

const Snippets: NextPage = () => {
  const snippet = api.snippet.getAll.useQuery()
  return (
    <>
      <Head>
        <title>All Snippets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex h-screen w-full items-center justify-center">
        <div>
          <h2 className="mb-6 text-7xl font-bold">
            {"I'm "}
            <span className="text-primary">
              Diogo
              <br />
            </span>
            Nogueira,
          </h2>
          <h1 className="text-xl leading-7 text-textdim">
            a <strong className="font-bold text-text">front-end developer</strong> who chose
            <br /> to hard code his life.
          </h1>
          <div className="flex flex-col gap-2">
            {snippet?.data?.map((snippet, idx) => (
              <div key={idx} className="flex flex-col gap-3 rounded bg-zinc-400 p-4">
                <span className="w-min rounded-full bg-background px-2">{snippet.language}</span>
                <span>{snippet.text}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

export default Snippets
