import * as DropdownMenu from "@radix-ui/react-dropdown-menu"
import type { GetServerSideProps, NextPage } from "next"
import { getSession } from "next-auth/react"
import Head from "next/head"
import { useRouter } from "next/router"
import { CaretDown } from "phosphor-react"
import { useState } from "react"
import { api } from "utils/api"
import { langs } from "utils/md-supported-langs"

const NewSnippet: NextPage = () => {
  const [language, setLanguage] = useState({ name: "Language", value: "" })
  const [code, setCode] = useState("")

  const snippetCreate = api.snippet.create.useMutation()

  const router = useRouter()

  async function handleCreateSnippet() {
    const createdSnippet = await snippetCreate.mutateAsync({ language: language.value, text: code })
    router.push(`/snippets/${createdSnippet.id}`)
  }

  return (
    <>
      <Head>
        <title>Create New Snippet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex h-screen w-full items-center justify-center">
        <div>
          <h1 className="mb-8 text-7xl font-bold">
            {"Create a new "}
            <span className="text-primary">Snippet</span>
          </h1>
          <p className="text-xl leading-7 text-textdim">Paste your code below and select the corresponding language.</p>
          <div className="grid grid-cols-[1fr_20%] items-center gap-4">
            <textarea
              value={code}
              rows={1}
              onChange={e => setCode(e.currentTarget.value)}
              className="scroll flex-1 resize-none rounded bg-background p-3 outline-none ring-2 ring-text"
            />
            <DropdownMenu.Root>
              <DropdownMenu.Trigger asChild>
                <button className="flex justify-between gap-3 rounded p-3 outline-none ring-2 ring-text hover:bg-black/5">
                  {language.name}
                  <CaretDown className="h-6 w-6" />
                </button>
              </DropdownMenu.Trigger>

              <DropdownMenu.Portal>
                <DropdownMenu.Content
                  sideOffset={6}
                  className="scroll max-h-[30vh] overflow-y-scroll rounded bg-background shadow-lg shadow-text/20">
                  <DropdownMenu.RadioGroup
                    className="divide-y divide-text/20"
                    value={language.value}
                    onValueChange={value => {
                      const newLang = langs.find(lang => lang.value === value)
                      setLanguage(newLang!)
                    }}>
                    {langs.map(lang => (
                      <DropdownMenu.RadioItem
                        key={lang.value}
                        value={lang.value}
                        className="cursor-pointer py-1 px-2 hover:bg-black/5">
                        {lang.name}
                      </DropdownMenu.RadioItem>
                    ))}
                  </DropdownMenu.RadioGroup>
                </DropdownMenu.Content>
              </DropdownMenu.Portal>
            </DropdownMenu.Root>
          </div>
          <button className="mt-4 w-full rounded  bg-primary p-3 text-background" onClick={handleCreateSnippet}>
            Submit
          </button>
        </div>
      </div>
    </>
  )
}

export default NewSnippet

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req })

  if (!session || session.user?.name !== "neru") {
    return {
      redirect: {
        destination: "/login",
        permanent: false
      }
    }
  }

  return { props: {} }
}
